### ISSUE TITLE
Yu-Gi-Oh SLUS01411

### ISSUE THREAD

**Issue by zigoraty** [pcercuei/lightrec#22] opened 2023-08-31 23:15 UTC
When attacking a card with the "square" button instead of "X", a 3D battle animation occurs, then the animation starts and after a few seconds the code dump occurs.
![20230831_182744](https://github.com/pcercuei/lightrec/assets/54875925/d01a6500-b297-4925-8dd9-2325699b5de9)

**Comment by pcercuei** [comment] 2023-09-04 12:14
I tested with SLES03948, and can't reproduce in WiiSX - it just works.

**Comment by pcercuei** [comment] 2023-09-04 13:12
Same with SLUS-01411.

It's possible that the bug you saw was the same as #21, which I just fixed a few hours ago; which would explain why I don't see it.

**Comment by zigoraty** [comment] 2023-09-04 13:47
Weird, I just tested it and the problem still occurs, but only when attacking a card with the square button
![20230904_104613](https://github.com/pcercuei/lightrec/assets/54875925/2492264f-bd70-4412-b398-75ddb2c7f807)

**Comment by zigoraty** [comment] 2023-09-04 13:54
![20230904_105231](https://github.com/pcercuei/lightrec/assets/54875925/9531e120-804a-4828-86ed-7a7639df5657)

**Comment by pcercuei** [comment] 2023-09-04 13:54
Well the pcsx-rearmed libretro core is not using the latest Lightrec yet.

**Comment by zigoraty** [comment] 2023-09-04 13:57
> Well the pcsx-rearmed libretro core is not using the latest Lightrec yet.

Oh, so that's the problem. Anyway thank you!

**Comment by Ploggy** [comment] 2023-09-04 14:03
@zigoraty issues fixed now just tested latest code :) all good.

**Comment by pcercuei** [comment] 2023-09-04 14:08
Closing as it's a duplicate of #21 which has been fixed already.

**Closed as not planned by pcercuei** 2023-09-04 14:08 UTC
